package memory

import (
	"database/sql"
	"fmt"
	"sort"
	"time"
)

// MemoryLink represents a typed connection between two memories.
type MemoryLink struct {
	ID         int64     `json:"id"`
	SourceID   int64     `json:"source_id"`
	TargetID   int64     `json:"target_id"`
	Relation   string    `json:"relation"`        // e.g. "related", "follows", "contradicts", "similar"
	Weight     float64   `json:"weight"`          // 0..1 strength
	AutoLinked bool      `json:"auto_linked"`     // generated by similarity engine
	Note       string    `json:"note,omitempty"`
	CreatedAt  time.Time `json:"created_at"`
}

// GraphNode is a memory node for visualization.
type GraphNode struct {
	ID         int64    `json:"id"`
	Label      string   `json:"label"`
	Content    string   `json:"content"`
	Tags       []string `json:"tags"`
	Source     string   `json:"source"`
	CategoryID *int64   `json:"category_id,omitempty"`
	Degree     int      `json:"degree"`
}

// GraphEdge is a link between memory nodes for visualization.
type GraphEdge struct {
	From     int64   `json:"from"`
	To       int64   `json:"to"`
	Relation string  `json:"relation"`
	Weight   float64 `json:"weight"`
	Auto     bool    `json:"auto"`
}

// GraphData wraps nodes + edges for the memory graph.
type GraphData struct {
	Nodes []GraphNode `json:"nodes"`
	Edges []GraphEdge `json:"edges"`
}

// EnsureLinksSchema creates the memory_links table if missing.
// Safe to call multiple times.
func EnsureLinksSchema(db *sql.DB) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS memory_links (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			source_id INTEGER NOT NULL,
			target_id INTEGER NOT NULL,
			relation TEXT DEFAULT 'related',
			weight REAL DEFAULT 0.5,
			auto_linked INTEGER DEFAULT 0,
			note TEXT DEFAULT '',
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			UNIQUE(source_id, target_id, relation),
			FOREIGN KEY (source_id) REFERENCES memories(id) ON DELETE CASCADE,
			FOREIGN KEY (target_id) REFERENCES memories(id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_memory_links_source ON memory_links(source_id)`,
		`CREATE INDEX IF NOT EXISTS idx_memory_links_target ON memory_links(target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_memory_links_relation ON memory_links(relation)`,
	}
	for _, s := range stmts {
		if _, err := db.Exec(s); err != nil {
			return fmt.Errorf("ensure memory_links: %w", err)
		}
	}
	return nil
}

// AddLink creates a manual link between two memories.
// Self-links are rejected. Duplicate (source,target,relation) is upserted (weight/note updated).
func (s *SQLiteStore) AddLink(sourceID, targetID int64, relation string, weight float64, note string) (*MemoryLink, error) {
	if sourceID == targetID {
		return nil, fmt.Errorf("tidak bisa link memory ke dirinya sendiri")
	}
	if relation == "" {
		relation = "related"
	}
	if weight <= 0 || weight > 1 {
		weight = 0.5
	}
	if err := EnsureLinksSchema(s.db); err != nil {
		return nil, err
	}

	// Verify both memories exist.
	var c int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM memories WHERE id IN (?, ?)`, sourceID, targetID).Scan(&c); err != nil {
		return nil, fmt.Errorf("verifikasi memory: %w", err)
	}
	if c < 2 {
		return nil, fmt.Errorf("salah satu memory id tidak ditemukan")
	}

	now := time.Now()
	_, err := s.db.Exec(
		`INSERT INTO memory_links (source_id, target_id, relation, weight, auto_linked, note, created_at)
		 VALUES (?, ?, ?, ?, 0, ?, ?)
		 ON CONFLICT(source_id, target_id, relation) DO UPDATE SET
			weight = excluded.weight,
			note = excluded.note,
			auto_linked = 0`,
		sourceID, targetID, relation, weight, note, now,
	)
	if err != nil {
		return nil, fmt.Errorf("simpan link: %w", err)
	}

	row := s.db.QueryRow(
		`SELECT id, source_id, target_id, relation, weight, auto_linked, note, created_at
		 FROM memory_links WHERE source_id=? AND target_id=? AND relation=?`,
		sourceID, targetID, relation,
	)
	link := &MemoryLink{}
	var auto int
	if err := row.Scan(&link.ID, &link.SourceID, &link.TargetID, &link.Relation, &link.Weight, &auto, &link.Note, &link.CreatedAt); err != nil {
		return nil, err
	}
	link.AutoLinked = auto == 1
	return link, nil
}

// RemoveLink deletes a link by ID.
func (s *SQLiteStore) RemoveLink(id int64) error {
	if err := EnsureLinksSchema(s.db); err != nil {
		return err
	}
	res, err := s.db.Exec(`DELETE FROM memory_links WHERE id=?`, id)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("link id %d tidak ditemukan", id)
	}
	return nil
}

// ListLinksFor returns all links touching a given memory id (either side).
func (s *SQLiteStore) ListLinksFor(memoryID int64) ([]MemoryLink, error) {
	if err := EnsureLinksSchema(s.db); err != nil {
		return nil, err
	}
	rows, err := s.db.Query(
		`SELECT id, source_id, target_id, relation, weight, auto_linked, note, created_at
		 FROM memory_links WHERE source_id=? OR target_id=? ORDER BY weight DESC, created_at DESC`,
		memoryID, memoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []MemoryLink
	for rows.Next() {
		var l MemoryLink
		var auto int
		if err := rows.Scan(&l.ID, &l.SourceID, &l.TargetID, &l.Relation, &l.Weight, &auto, &l.Note, &l.CreatedAt); err != nil {
			return nil, err
		}
		l.AutoLinked = auto == 1
		out = append(out, l)
	}
	return out, nil
}

// AutoLinkOptions controls automatic similarity-based linking.
type AutoLinkOptions struct {
	WorkspaceID int64
	Threshold   float64 // minimum cosine similarity (0..1). default 0.78
	MaxPerNode  int     // top-k links to keep per node. default 5
	Replace     bool    // remove previous auto-links before re-running
}

// AutoLink builds similarity links between memories with embeddings.
// Returns the number of links inserted.
func (s *SQLiteStore) AutoLink(opts AutoLinkOptions) (int, error) {
	if err := EnsureLinksSchema(s.db); err != nil {
		return 0, err
	}
	if opts.Threshold <= 0 {
		opts.Threshold = 0.78
	}
	if opts.MaxPerNode <= 0 {
		opts.MaxPerNode = 5
	}

	if opts.Replace {
		if _, err := s.db.Exec(`DELETE FROM memory_links WHERE auto_linked=1`); err != nil {
			return 0, fmt.Errorf("bersihkan auto-links: %w", err)
		}
	}

	// Load all memories with embeddings for the workspace.
	q := `SELECT id, embedding FROM memories
		  WHERE embedding IS NOT NULL AND length(embedding) > 0`
	args := []interface{}{}
	if opts.WorkspaceID > 0 {
		q += ` AND (workspace_id = ? OR workspace_id IS NULL)`
		args = append(args, opts.WorkspaceID)
	}
	rows, err := s.db.Query(q, args...)
	if err != nil {
		return 0, err
	}
	type embRow struct {
		id  int64
		emb []float32
	}
	var items []embRow
	for rows.Next() {
		var id int64
		var blob []byte
		if err := rows.Scan(&id, &blob); err != nil {
			rows.Close()
			return 0, err
		}
		v := blobToFloat32(blob)
		if len(v) == 0 {
			continue
		}
		items = append(items, embRow{id: id, emb: v})
	}
	rows.Close()

	if len(items) < 2 {
		return 0, nil
	}

	// For each node, keep top-k most similar peers above threshold.
	type cand struct {
		other int64
		sim   float64
	}
	now := time.Now()
	tx, err := s.db.Begin()
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`INSERT INTO memory_links (source_id, target_id, relation, weight, auto_linked, note, created_at)
		 VALUES (?, ?, 'similar', ?, 1, '', ?)
		 ON CONFLICT(source_id, target_id, relation) DO UPDATE SET
			weight = excluded.weight,
			auto_linked = 1`,
	)
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	inserted := 0
	for i := range items {
		var cands []cand
		for j := range items {
			if i == j {
				continue
			}
			sim := cosineSimilarity(items[i].emb, items[j].emb)
			if sim >= opts.Threshold {
				cands = append(cands, cand{other: items[j].id, sim: sim})
			}
		}
		if len(cands) == 0 {
			continue
		}
		sort.Slice(cands, func(a, b int) bool { return cands[a].sim > cands[b].sim })
		if len(cands) > opts.MaxPerNode {
			cands = cands[:opts.MaxPerNode]
		}
		for _, c := range cands {
			// Always store with smaller id as source for canonical undirected edge.
			a, b := items[i].id, c.other
			if a > b {
				a, b = b, a
			}
			if _, err := stmt.Exec(a, b, c.sim, now); err != nil {
				return 0, err
			}
			inserted++
		}
	}

	if err := tx.Commit(); err != nil {
		return 0, err
	}
	return inserted, nil
}

// BuildGraph returns nodes and edges for visualization within a workspace.
// limit caps the number of nodes returned (most recent first). 0 = no limit.
func (s *SQLiteStore) BuildGraph(workspaceID int64, limit int) (*GraphData, error) {
	if err := EnsureLinksSchema(s.db); err != nil {
		return nil, err
	}

	// Pull memories.
	q := `SELECT id, content, tags, source, category_id
		  FROM memories
		  WHERE (workspace_id = ? OR workspace_id IS NULL OR ? = 0)
		  ORDER BY created_at DESC`
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d", limit)
	}
	rows, err := s.db.Query(q, workspaceID, workspaceID)
	if err != nil {
		return nil, err
	}

	idSet := make(map[int64]bool)
	nodes := make([]GraphNode, 0, 64)
	for rows.Next() {
		var n GraphNode
		var tagsJSON sql.NullString
		var catID sql.NullInt64
		if err := rows.Scan(&n.ID, &n.Content, &tagsJSON, &n.Source, &catID); err != nil {
			rows.Close()
			return nil, err
		}
		n.Tags = parseTagsFromJSON(tagsJSON.String)
		if catID.Valid {
			v := catID.Int64
			n.CategoryID = &v
		}
		// Build a short label from content.
		n.Label = shortLabel(n.Content, 48)
		idSet[n.ID] = true
		nodes = append(nodes, n)
	}
	rows.Close()

	if len(nodes) == 0 {
		return &GraphData{Nodes: []GraphNode{}, Edges: []GraphEdge{}}, nil
	}

	// Pull edges that touch our nodes only.
	erows, err := s.db.Query(
		`SELECT source_id, target_id, relation, weight, auto_linked FROM memory_links`,
	)
	if err != nil {
		return nil, err
	}
	defer erows.Close()

	degree := make(map[int64]int)
	edges := make([]GraphEdge, 0, 64)
	for erows.Next() {
		var e GraphEdge
		var auto int
		if err := erows.Scan(&e.From, &e.To, &e.Relation, &e.Weight, &auto); err != nil {
			return nil, err
		}
		if !idSet[e.From] || !idSet[e.To] {
			continue
		}
		e.Auto = auto == 1
		edges = append(edges, e)
		degree[e.From]++
		degree[e.To]++
	}

	for i := range nodes {
		nodes[i].Degree = degree[nodes[i].ID]
	}

	return &GraphData{Nodes: nodes, Edges: edges}, nil
}

// shortLabel returns a single-line preview of content for use as a graph label.
func shortLabel(content string, maxLen int) string {
	s := ""
	for _, r := range content {
		if r == '\n' || r == '\r' || r == '\t' {
			r = ' '
		}
		s += string(r)
		if len(s) >= maxLen {
			break
		}
	}
	if len(content) > len(s) {
		s += "…"
	}
	return s
}
