package discord

import (
	"strings"
	"testing"
)

func TestGeneratePRDMarkdown(t *testing.T) {
	md := GeneratePRDMarkdown(PRDAnswers{
		ProductName:  "Discord PRD Bot",
		Idea:         "Bot Discord untuk membuat PRD dari pilihan button.",
		ProductType:  "Bot/Automation",
		TargetUser:   "Developer",
		Platform:     "Discord Bot",
		Scope:        "MVP",
		WorkflowPlan: "Agile Sprints",
		DiagramFlow:  "Flowchart & Sequence",
		DetailLevel:  "Lengkap",
	})
	for _, want := range []string{
		"# PRD: Discord PRD Bot",
		"## 1. Overview",
		"## 8. Functional Requirements",
		"## 11. Flow Alur Tahapan & Diagram Visual",
		"### User Flowchart Diagram",
		"### Sequence Diagram (System Interaction)",
		"## 12. Workflow & Execution Plan",
		"Model Rencana Kerja: **Agile Sprints**",
		"gantt",
		"## 13. Chat Flow / Plain Mode Flow",
		"Bot  : Halo, saya bantu buat PRD",
		"## 15. Risks & Mitigations",
		"Generated by Smara Discord PRD Wizard",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("markdown missing %q\n%s", want, md)
		}
	}
}

func TestPRDFileName(t *testing.T) {
	got := PRDFileName("Discord PRD Bot!")
	if got != "PRD_discord-prd-bot.md" {
		t.Fatalf("unexpected filename: %s", got)
	}
}

func TestGeneratePRDMarkdown_FoodProductIdea(t *testing.T) {
	answers := PRDAnswers{
		Idea:         "buatkan website produk makanan instan yang menyajikan mie",
		ProductType:  "Web App",
		TargetUser:   "Consumer",
		Platform:     "Web",
		Scope:        "Enterprise",
		WorkflowPlan: "Phase-based",
		DiagramFlow:  "Semua Diagram",
		DetailLevel:  "Lengkap",
	}

	md := GeneratePRDMarkdown(answers)

	// Check clean product name inference
	if strings.Contains(md, "# PRD: Buatkan Website") {
		t.Fatalf("Product name should not contain lead-in verb 'Buatkan Website'\nGot: %s", md)
	}

	// Check domain contextual content (food/mie instan)
	expectedPhrases := []string{
		"makanan instan",
		"katalog",
		"mie instan",
		"### User Flowchart Diagram",
		"### Sequence Diagram (System Interaction)",
		"### State Transition Diagram",
		"gantt",
		"Model Rencana Kerja: **Phase-based**",
		"Generated by Smara Discord PRD Wizard",
	}

	for _, want := range expectedPhrases {
		if !strings.Contains(md, want) {
			t.Fatalf("expected markdown to contain %q, but it didn't.\nFull Output:\n%s", want, md)
		}
	}
}

func TestGeneratePRDMarkdown_FinancialAnalyticsIdea(t *testing.T) {
	answers := PRDAnswers{
		Idea:         "buatkan website analisis keuangan statistik",
		ProductType:  "Web App",
		TargetUser:   "Business",
		Platform:     "Multi-platform",
		TechStack:    "Fullstack JS/TS",
		Scope:        "Enterprise",
		Priority:     "Premium UX & Design",
		WorkflowPlan: "Phase-based",
		DiagramFlow:  "Semua Diagram",
		DetailLevel:  "Lengkap",
	}

	md := GeneratePRDMarkdown(answers)

	if strings.Contains(md, "# PRD: Buatkan Website") {
		t.Fatalf("Product name should not contain lead-in verb 'Buatkan Website'\nGot: %s", md)
	}

	if strings.Contains(md, "memfasilitasi kebutuhan buatkan website") {
		t.Fatalf("Overview text should not contain raw lead-in phrase 'buatkan website'\nGot: %s", md)
	}

	expectedPhrases := []string{
		"# PRD: Website Analisis Keuangan Statistik",
		"analisis keuangan",
		"rasio finansial",
		"pemrosesan statistik",
		"### User Flowchart Diagram",
		"### Sequence Diagram (System Interaction)",
		"### State Transition Diagram",
		"gantt",
		"Fullstack JS/TS",
		"Premium UX & Design",
	}

	for _, want := range expectedPhrases {
		if !strings.Contains(md, want) {
			t.Fatalf("expected markdown to contain %q, but it didn't.\nFull Output:\n%s", want, md)
		}
	}
}

