package discord

import (
	"strings"
	"testing"
)

func TestGeneratePRDMarkdown(t *testing.T) {
	md := GeneratePRDMarkdown(PRDAnswers{
		ProductName: "Discord PRD Bot",
		Idea:        "Bot Discord untuk membuat PRD dari pilihan button.",
		ProductType: "Bot/Automation",
		TargetUser:  "Developer",
		Platform:    "Discord Bot",
		Scope:       "MVP",
		DetailLevel: "Lengkap",
	})
	for _, want := range []string{"# PRD: Discord PRD Bot", "## 1. Overview", "## 8. Functional Requirements", "## 11. Flow Alur Tahapan", "## 12. Chat Flow / Plain Mode Flow", "Bot  : Halo, saya bantu buat PRD", "## 14. Risks & Mitigations", "Generated by Smara Discord PRD Wizard"} {
		if !strings.Contains(md, want) {
			t.Fatalf("markdown missing %q\n%s", want, md)
		}
	}
}

func TestPRDFileName(t *testing.T) {
	got := PRDFileName("Discord PRD Bot!")
	if got != "PRD_discord-prd-bot.md" {
		t.Fatalf("unexpected filename: %s", got)
	}
}
