// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveMemory(arg1) {
  return window['go']['main']['App']['ArchiveMemory'](arg1);
}

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function ArchiveWorkspace(arg1) {
  return window['go']['main']['App']['ArchiveWorkspace'](arg1);
}

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteArchivedMemory(arg1) {
  return window['go']['main']['App']['DeleteArchivedMemory'](arg1);
}

export function DeleteArchivedSession(arg1) {
  return window['go']['main']['App']['DeleteArchivedSession'](arg1);
}

export function GetArchivedMemories() {
  return window['go']['main']['App']['GetArchivedMemories']();
}

export function GetArchivedSessions() {
  return window['go']['main']['App']['GetArchivedSessions']();
}

export function GetArchivedWorkspaces() {
  return window['go']['main']['App']['GetArchivedWorkspaces']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UnarchiveMemory(arg1) {
  return window['go']['main']['App']['UnarchiveMemory'](arg1);
}

export function UnarchiveSession(arg1) {
  return window['go']['main']['App']['UnarchiveSession'](arg1);
}

export function UnarchiveWorkspace(arg1) {
  return window['go']['main']['App']['UnarchiveWorkspace'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
