// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {llm} from '../models';
import {session} from '../models';
import {memory} from '../models';

export function Ask(arg1:string):Promise<string>;

export function CreateSession(arg1:string):Promise<string>;

export function GetConfig():Promise<config.SmaraConfig>;

export function GetSessionHistory():Promise<Array<llm.Message>>;

export function GetSessions():Promise<Array<session.Session>>;

export function GetTools():Promise<Array<Record<string, any>>>;

export function GetWorkspaces():Promise<Array<memory.Workspace>>;

export function Greet(arg1:string):Promise<string>;

export function SetWorkspace(arg1:number):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;

export function UpdateConfig(arg1:config.SmaraConfig):Promise<void>;
