// Package workflow implements the agentic workflow engine with orchestrated multi-agent execution.
package workflow

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/gede-cahya/Smara-CLI/internal/agent"
	"github.com/gede-cahya/Smara-CLI/internal/llm"
)

// Domain represents the detected professional domain of a user request.
type Domain struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	TypicalRoles []string `json:"typical_roles"`
}

// Blueprint represents the structured project plan generated by the Orchestrator.
type Blueprint struct {
	ProjectName  string      `json:"project_name"`
	Description  string      `json:"description"`
	Domain       string      `json:"domain"`
	PRD          string      `json:"prd"`
	Architecture string      `json:"architecture"`
	Agents       []AgentSpec `json:"agents"`
}

// AgentSpec defines a specialized worker agent to spawn.
type AgentSpec struct {
	Role        string   `json:"role"`
	Description string   `json:"description"`
	Skills      []string `json:"skills"`
	Tasks       []Task   `json:"tasks"`
	DependsOn   []string `json:"depends_on,omitempty"`
}

// Task defines a unit of work within an agent spec.
type Task struct {
	ID          string                 `json:"id"`
	Description string                 `json:"description"`
	Type        string                 `json:"type,omitempty"` // "llm" or "mcp"
	MCPServer   string                 `json:"mcp_server,omitempty"`
	ToolName    string                 `json:"tool_name,omitempty"`
	ToolArgs    map[string]interface{} `json:"tool_args,omitempty"`
}

// DomainRegistry maps domain keywords to professional domains.
var DomainRegistry = map[string]Domain{
	"software_engineering": {
		Name:         "software_engineering",
		Description:  "Pengembangan perangkat lunak, web app, SaaS, mobile app, API, dan sistem software.",
		TypicalRoles: []string{"frontend", "backend", "database", "devops", "designer", "qa"},
	},
	"marketing": {
		Name:         "marketing",
		Description:  "Marketing campaign, content creation, SEO, social media, branding, dan digital marketing.",
		TypicalRoles: []string{"content_strategist", "copywriter", "visual_designer", "seo_analyst", "campaign_manager"},
	},
	"legal": {
		Name:         "legal",
		Description:  "Legal drafting, contract review, compliance analysis, legal research, dan litigation support.",
		TypicalRoles: []string{"legal_researcher", "contract_drafter", "compliance_checker", "litigation_analyst"},
	},
	"data_analysis": {
		Name:         "data_analysis",
		Description:  "Data processing, visualization, business intelligence, statistical analysis, dan reporting.",
		TypicalRoles: []string{"data_engineer", "data_scientist", "visualization_expert", "bi_analyst"},
	},
	"graphic_design": {
		Name:         "graphic_design",
		Description:  "Brand identity, logo design, illustration, UI/UX design, typography, dan visual design.",
		TypicalRoles: []string{"brand_strategist", "illustrator", "typography_expert", "ux_researcher"},
	},
	"reverse_engineering": {
		Name:         "reverse_engineering",
		Description:  "Binary analysis, malware research, firmware reverse engineering, source-code archaeology, dan static analysis.",
		TypicalRoles: []string{"binary_analyst", "code_archaeologist"},
	},
}

// DetectDomain attempts to classify the user's prompt into a professional domain.
func DetectDomain(prompt string) Domain {
	lower := strings.ToLower(prompt)

	domainScores := make(map[string]int)

	// Software engineering keywords
	softwareKWs := []string{"web", "app", "saas", "api", "frontend", "backend", "database", "server", "code", "program", "software", "development", "deploy", "docker", "react", "nextjs", "vue", "angular", "node", "python", "go", "java", "typescript"}
	for _, kw := range softwareKWs {
		if strings.Contains(lower, kw) {
			domainScores["software_engineering"] += 2
		}
	}

	// Marketing keywords
	marketingKWs := []string{"campaign", "marketing", "seo", "ads", "branding", "social media", "content", "copywriting", "email marketing", "lead generation", "conversion", "funnel", "advertising"}
	for _, kw := range marketingKWs {
		if strings.Contains(lower, kw) {
			domainScores["marketing"] += 2
		}
	}

	// Legal keywords
	legalKWs := []string{"contract", "legal", "hukum", "kontrak", "agreement", "clause", "compliance", "litigation", "notary", "advokat", "terms of service", "privacy policy", "nda", "memorandum"}
	for _, kw := range legalKWs {
		if strings.Contains(lower, kw) {
			domainScores["legal"] += 2
		}
	}

	// Data analysis keywords
	dataKWs := []string{"data analysis", "analisis data", "dataset", "visualization", "chart", "dashboard", "bi ", "business intelligence", "sql", "pandas", "excel", "report", "statistics", "machine learning", "ml "}
	for _, kw := range dataKWs {
		if strings.Contains(lower, kw) {
			domainScores["data_analysis"] += 2
		}
	}

	// Graphic design keywords
	designKWs := []string{"logo", "design", "desain", "illustration", "illustrasi", "brand identity", "ui/ux", "typography", "mockup", "wireframe", "brand guideline", "color palette", "poster", "brochure"}
	for _, kw := range designKWs {
		if strings.Contains(lower, kw) {
			domainScores["graphic_design"] += 2
		}
	}

	// Reverse engineering keywords
	reKWs := []string{"reverse engineering", "reverse-engineer", "firmware", "binary", "malware", "disassembly", "decompile", "elf", "pe ", "mach-o", "static analysis", "call graph", "dependency map", "string extraction", "entropy", "packer", "signature scan", "yara", "hex dump", "code archaeology"}
	for _, kw := range reKWs {
		if strings.Contains(lower, kw) {
			domainScores["reverse_engineering"] += 2
		}
	}

	// Find highest scoring domain
	var bestDomain string
	var bestScore int
	for domain, score := range domainScores {
		if score > bestScore {
			bestScore = score
			bestDomain = domain
		}
	}

	if bestDomain != "" && bestScore >= 2 {
		return DomainRegistry[bestDomain]
	}

	// Default to software_engineering if ambiguous but contains "buatkan" or "buat"
	if strings.Contains(lower, "buatkan") || strings.Contains(lower, "buat") || strings.Contains(lower, "create") || strings.Contains(lower, "generate") {
		return DomainRegistry["software_engineering"]
	}

	return Domain{
		Name:         "general",
		Description:  "General project requiring multi-disciplinary approach.",
		TypicalRoles: []string{"researcher", "writer", "analyst", "reviewer"},
	}
}

// blueprintSchema is the JSON schema prompt for LLM blueprint generation.
const blueprintSchema = `{
  "project_name": "string",
  "description": "string",
  "domain": "string (software_engineering|marketing|legal|data_analysis|graphic_design|reverse_engineering|general)",
  "prd": "string (markdown)",
  "architecture": "string (markdown - workflow design for the domain)",
  "agents": [
    {
      "role": "string (any role name - dynamically invented based on domain needs)",
      "description": "string",
      "skills": ["string"],
      "tasks": [
        {
          "id": "string",
          "description": "string",
          "type": "llm or mcp",
          "mcp_server": "string (optional)",
          "tool_name": "string (optional)"
        }
      ],
      "depends_on": ["string (role names)"]
    }
  ]
}`

// OrchestratorPrompt is the domain-aware system prompt for the Lead Architect / PM role.
const OrchestratorPrompt = `Kamu adalah Lead Architect / Project Manager AI yang domain-agnostic.
Tugasmu adalah menganalisis permintaan user, mendeteksi domain profesionalnya, membuat Product Requirements Document (PRD) sesuai domain, mendesain workflow/aritektur, dan memecahnya menjadi task pipeline untuk agen-agen spesialis.

LANGKAH-LANGKAH:
1. DETEKSI domain profesional dari permintaan user.
2. BUAT PRD berisi deliverables, requirements, dan acceptance criteria sesuai domain.
3. DESAIN workflow/aritektur yang sesuai domain (bukan hanya software stack).
4. PECAH menjadi task pipeline dengan dependensi antar agen.

DOMAIN YANG DIDUKUNG:
- software_engineering: web/app, API, database, deployment
- marketing: campaign, content, SEO, branding, social media
- legal: contracts, compliance, legal research, drafting
- data_analysis: data processing, visualization, BI, reporting
- graphic_design: brand identity, logo, illustration, UI/UX
- reverse_engineering: binary/firmware analysis, malware research, source-code archaeology, static analysis
- general: multi-disciplinary projects

FORMAT OUTPUT (JSON sesuai schema):
- project_name: nama proyek singkat
- description: deskripsi proyek 1-2 kalimat
- domain: detected domain name
- prd: markdown PRD lengkap (domain-specific)
- architecture: markdown dokumentasi workflow/aritektur
- agents: array agen spesialis (role names DIBUAT SECARA DINAMIS sesuai kebutuhan domain, BUKAN fixed list)

Setiap agen harus memiliki:
- role: nama peran (bebas, sesuai domain)
- description: apa yang dikerjakan secara spesifik
- skills: keahlian yang dibutuhkan
- tasks: daftar task spesifik
- depends_on: role yang harus selesai dulu (untuk DAG execution)

PENTING — MCP TOOL USAGE:
- Jika task type = "mcp", mcp_server HARUS exact name dari server yang tersedia (lihat "MCP Servers tersedia")
- tool_name HARUS exact name dari tool yang ada di server tersebut — JANGAN invent tool names
- Kalau tidak yakin tool name yang benar, gunakan type = "llm" saja
- Contoh tool yang valid: generate_screen_from_text, create_design_system, create_project (lihat exact names di "MCP Servers tersedia")

CONTOH AGEN PER DOMAIN:
Software: FrontendDev, BackendDev, DatabaseArchitect, DevOpsEngineer, SecurityAuditor
Marketing: ContentStrategist, Copywriter, VisualDesigner, SEOAnalyst, CampaignManager
Legal: LegalResearcher, ContractDrafter, ComplianceChecker, LitigationAnalyst
Data: DataEngineer, DataScientist, VisualizationExpert, BIAnalyst
Design: BrandStrategist, Illustrator, TypographyExpert, UXResearcher
Reverse Engineering: BinaryAnalyst, CodeArchaeologist

Output HANYA JSON valid sesuai schema. Tidak ada teks di luar JSON.`

// GenerateBlueprint creates a Blueprint from a user prompt using the LLM.
func GenerateBlueprint(supervisor *agent.Supervisor, prompt string) (Blueprint, error) {
	return GenerateBlueprintWithProvider(supervisor.GetProvider(), supervisor.GetMCPInfo(), prompt)
}

// GenerateBlueprintWithProvider creates a Blueprint using a direct LLM provider.
// extractJSON tries to extract a valid JSON substring from raw LLM output.
// It handles: JSON inside a quoted string, markdown code fences, bare JSON, etc.
func extractJSON(raw string) string {
	raw = strings.TrimSpace(raw)

	// Case 1: the entire response is a quoted JSON string → unquote it
	if strings.HasPrefix(raw, `"`) && strings.HasSuffix(raw, `"`) {
		if unquoted, err := strconv.Unquote(raw); err == nil {
			raw = strings.TrimSpace(unquoted)
		}
	}

	// Case 2: find first { or [
	idx := strings.IndexAny(raw, "{[")
	if idx < 0 {
		return raw
	}

	// Case 3: strip markdown fences (```json ... ```)
	re := regexp.MustCompile("(?s)```(?:json)?\\s*(\\{.*?\\})\\s*```")
	if m := re.FindStringSubmatch(raw); len(m) > 1 {
		return m[1]
	}

	return raw[idx:]
}

func GenerateBlueprintWithProvider(provider llm.Provider, mcpInfo map[string]agent.MCPServerInfo, prompt string) (Blueprint, error) {
	var bp Blueprint
	if strings.TrimSpace(prompt) == "" {
		return bp, fmt.Errorf("prompt tidak boleh kosong")
	}

	var mcpDescs []string
	for name, info := range mcpInfo {
		if !info.Connected {
			continue
		}
		toolNames := make([]string, 0, len(info.Tools))
		for _, t := range info.Tools {
			toolNames = append(toolNames, t.Name)
		}
		mcpDescs = append(mcpDescs, fmt.Sprintf("- %s: %s", name, strings.Join(toolNames, ", ")))
	}

	mcpContext := ""
	if len(mcpDescs) > 0 {
		mcpContext = "\nMCP Servers tersedia:\n" + strings.Join(mcpDescs, "\n")
	}

	messages := []llm.Message{
		{Role: llm.RoleSystem, Content: OrchestratorPrompt},
		{Role: llm.RoleSystem, Content: "Schema JSON yang wajib diikuti:\n" + blueprintSchema + mcpContext},
		{Role: llm.RoleUser, Content: prompt},
	}

	resp, err := provider.Chat(messages)
	if err != nil {
		return bp, fmt.Errorf("gagal generate blueprint: %w", err)
	}

	// Extract JSON from response (handle escaped strings, markdown fences, bare JSON)
	content := extractJSON(resp.Content)

	if err := json.Unmarshal([]byte(content), &bp); err != nil {
		// Retry once with error feedback
		retryMsgs := append(messages,
			llm.Message{Role: llm.RoleAssistant, Content: resp.Content},
			llm.Message{Role: llm.RoleUser, Content: fmt.Sprintf("JSON tidak valid: %v. Mohon ulangi dengan format JSON yang benar sesuai schema.", err)},
		)
		resp2, err2 := provider.Chat(retryMsgs)
		if err2 != nil {
			return bp, fmt.Errorf("gagal generate blueprint (retry): %w", err2)
		}
		content2 := extractJSON(resp2.Content)

		if err := json.Unmarshal([]byte(content2), &bp); err != nil {
			return bp, fmt.Errorf("gagal parse blueprint JSON setelah retry: %w", err)
		}
	}

	return bp, nil
}

// ToJSON serializes a Blueprint to JSON.
func (bp *Blueprint) ToJSON() ([]byte, error) {
	return json.MarshalIndent(bp, "", "  ")
}
