// Package workflow implements the agentic workflow engine with orchestrated multi-agent execution.
package workflow

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/gede-cahya/Smara-CLI/pkg/agent"
	"github.com/gede-cahya/Smara-CLI/pkg/llm"
)

// Blueprint represents the structured project plan generated by the Orchestrator.
type Blueprint struct {
	ProjectName  string     `json:"project_name"`
	Description  string     `json:"description"`
	PRD          string     `json:"prd"`
	Architecture string     `json:"architecture"`
	Agents       []AgentSpec `json:"agents"`
}

// AgentSpec defines a specialized worker agent to spawn.
type AgentSpec struct {
	Role        string   `json:"role"`
	Description string   `json:"description"`
	Skills      []string `json:"skills"`
	Tasks       []Task   `json:"tasks"`
	DependsOn   []string `json:"depends_on,omitempty"`
}

// Task defines a unit of work within an agent spec.
type Task struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Type        string `json:"type,omitempty"` // "llm" or "mcp"
	MCPServer   string `json:"mcp_server,omitempty"`
	ToolName    string `json:"tool_name,omitempty"`
}

// blueprintSchema is the JSON schema prompt for LLM blueprint generation.
const blueprintSchema = `{
  "project_name": "string",
  "description": "string",
  "prd": "string (markdown)",
  "architecture": "string (markdown)",
  "agents": [
    {
      "role": "string (frontend|backend|database|devops|designer|qa|custom)",
      "description": "string",
      "skills": ["string"],
      "tasks": [
        {
          "id": "string",
          "description": "string",
          "type": "llm or mcp",
          "mcp_server": "string (optional)",
          "tool_name": "string (optional)"
        }
      ],
      "depends_on": ["string (role names)"]
    }
  ]
}`

// OrchestratorPrompt is the system prompt for the Lead Architect / PM role.
const OrchestratorPrompt = `Kamu adalah Lead Architect / Project Manager AI.
Tugasmu adalah menganalisis permintaan user, membuat Product Requirements Document (PRD), mendesain arsitektur teknis, dan memecahnya menjadi task pipeline untuk agen-agen spesialis.

LANGKAH-LANGKAH:
1. ANALISIS permintaan user dengan teliti.
2. BUAT PRD berisi fitur-fitur utama, user stories, dan acceptance criteria.
3. DESAIN arsitektur teknis (UI layer, API layer, DB layer, infrastruktur).
4. PECAH menjadi task pipeline dengan dependensi antar agen.

FORMAT OUTPUT (JSON sesuai schema):
- project_name: nama proyek singkat
- description: deskripsi proyek 1-2 kalimat
- prd: markdown PRD lengkap
- architecture: markdown dokumentasi arsitektur
- agents: array agen spesialis (frontend, backend, database, devops, designer, qa)

Setiap agen harus memiliki:
- role: nama peran
- description: apa yang dikerjakan
- skills: keahlian yang dibutuhkan
- tasks: daftar task spesifik
- depends_on: role yang harus selesai dulu (untuk DAG execution)

Gunakan tools yang tersedia untuk setiap role:
- frontend → stitch, figma (UI/UX)
- backend → terminal, file, code (API/logic)
- database → sql, terminal (schema/query)
- devops → deploy, docker, ssh (deployment)
- designer → figma, stitch (desain)
- qa → review, test (validasi)

Output HANYA JSON valid sesuai schema. Tidak ada teks di luar JSON.`

// GenerateBlueprint creates a Blueprint from a user prompt using the LLM.
func GenerateBlueprint(supervisor *agent.Supervisor, prompt string) (Blueprint, error) {
	var bp Blueprint
	return bp, fmt.Errorf("GenerateBlueprint requires provider injection: use GenerateBlueprintWithProvider")
}

// GenerateBlueprintWithProvider creates a Blueprint using a direct LLM provider.
func GenerateBlueprintWithProvider(provider llm.Provider, mcpInfo map[string]agent.MCPServerInfo, prompt string) (Blueprint, error) {
	var bp Blueprint

	var mcpDescs []string
	for name, info := range mcpInfo {
		if !info.Connected {
			continue
		}
		toolNames := make([]string, 0, len(info.Tools))
		for _, t := range info.Tools {
			toolNames = append(toolNames, t.Name)
		}
		mcpDescs = append(mcpDescs, fmt.Sprintf("- %s: %s", name, strings.Join(toolNames, ", ")))
	}

	mcpContext := ""
	if len(mcpDescs) > 0 {
		mcpContext = "\nMCP Servers tersedia:\n" + strings.Join(mcpDescs, "\n")
	}

	messages := []llm.Message{
		{Role: llm.RoleSystem, Content: OrchestratorPrompt},
		{Role: llm.RoleSystem, Content: "Schema JSON yang wajib diikuti:\n" + blueprintSchema + mcpContext},
		{Role: llm.RoleUser, Content: prompt},
	}

	resp, err := provider.Chat(messages)
	if err != nil {
		return bp, fmt.Errorf("gagal generate blueprint: %w", err)
	}

	// Extract JSON from response (handle markdown code blocks)
	content := resp.Content
	content = strings.TrimSpace(content)
	if idx := strings.Index(content, "```json"); idx != -1 {
		content = content[idx+7:]
		if end := strings.Index(content, "```"); end != -1 {
			content = content[:end]
		}
	} else if idx := strings.Index(content, "```"); idx != -1 {
		content = content[idx+3:]
		if end := strings.Index(content, "```"); end != -1 {
			content = content[:end]
		}
	}
	content = strings.TrimSpace(content)

	if err := json.Unmarshal([]byte(content), &bp); err != nil {
		// Retry once with error feedback
		retryMsgs := append(messages,
			llm.Message{Role: llm.RoleAssistant, Content: resp.Content},
			llm.Message{Role: llm.RoleUser, Content: fmt.Sprintf("JSON tidak valid: %v. Mohon ulangi dengan format JSON yang benar sesuai schema.", err)},
		)
		resp2, err2 := provider.Chat(retryMsgs)
		if err2 != nil {
			return bp, fmt.Errorf("gagal generate blueprint (retry): %w", err2)
		}
		content2 := resp2.Content
		content2 = strings.TrimSpace(content2)
		if idx := strings.Index(content2, "```json"); idx != -1 {
			content2 = content2[idx+7:]
			if end := strings.Index(content2, "```"); end != -1 {
				content2 = content2[:end]
			}
		} else if idx := strings.Index(content2, "```"); idx != -1 {
			content2 = content2[idx+3:]
			if end := strings.Index(content2, "```"); end != -1 {
				content2 = content2[:end]
			}
		}
		content2 = strings.TrimSpace(content2)
		if err := json.Unmarshal([]byte(content2), &bp); err != nil {
			return bp, fmt.Errorf("gagal parse blueprint JSON setelah retry: %w", err)
		}
	}

	return bp, nil
}

// ToJSON serializes a Blueprint to JSON.
func (bp *Blueprint) ToJSON() ([]byte, error) {
	return json.MarshalIndent(bp, "", "  ")
}
